enum ToolbarEvents {
  UNDO = "undo",
  REDO = "redo",
  NORMAL_FONT_SIZE = "normal-font-size",
  TITLE_FONT_SIZE = "title-font-size",
  SUBTITLE_FONT_SIZE = "subtitle-font-size",
  TITLE_1_FONT_SIZE = "title-1-font-size",
  TITLE_2_FONT_SIZE = "title-2-font-size",
  TITLE_3_FONT_SIZE = "title-3-font-size",
  OPEN_FONTS_POPUP = "open-fonts-pop-up",
  INCREASE_FONT_SIZE = "increase-font-size",
  DECREASE_FONT_SIZE = "decrease-font-size",
  BOLD = "bold",
  ITALIC = "italic",
  STRIKE_LINE = "strike-line",
  OPEN_FONT_COLOR_POP_UP = "open-font-color-pop-up",
  OPEN_FONT_BACKGROUND_POP_UP = "open-font-background-pop-up",
  OPEN_LINK_POP_UP = "open-link-pop-up",
  OPEN_IMAGE_POP_UP = "open-image-pop-up",
  OPEN_COMMENTS_POP_UP = "open-comments-pop-up",
  OPEN_INDENT_POP_UP = "open-indent-pop-up",
  CHECK_LIST = "check-list",
  OPEN_LIST_POP_UP = "open-list-pop-up",
  TAB_LEFT = "tab-left",
  TAB_RIGHT = "tab-right",
  CLEAN_TEXT = "clean-text",
  ROOT = "root",
  TABLE = "table",
}

export { ToolbarEvents };
